### PR TITLE
djgpp patches

### PR DESCRIPTION
**Pull request by jwt27**

### CODE REVIEW

**Comment by jwt27** [comment]
@skitt I am staging and separating out the djgpp patches to binutils here so they can be submitted upstream.  In the process I'm making some changes so that less target-independent code is touched.

Now I also ran into the problem you found, where `bfd->sections` ends up being a null pointer.  I went through the patches in your Debian package but couldn't find what you changed.  Did you end up fixing this, and if so, would you mind sharing the solution?

**Comment by jwt27** [comment]
Disregard that message, I found it.  Fixed now.

**Comment by skitt** [comment]
@jwt27 cool, thanks for looking into this. I hadn’t separated the fixes out because I was just hiding the problem, not really handling it...

**Comment by jwt27** [comment]
I haven't really studied how this works either so I fixed it the same way as you did.  I don't see under what circumstances you could have a bfd with no sections, so it was probably never an issue in real-world scenarios, only in some artificial test cases.

**Comment by jwt27** [comment]
This has been applied upstream now (commits 0fe0f2d and f717994) :)

**Comment by stsp** [comment]
Cool!
And I suppose in PPA we have them too?
Maybe you can then increase the "no envseg"
message to test the larger stub right away. :)

**Comment by skitt** [comment]
Very nice, thanks for taking care of this!

**Comment by stsp** [comment]
Ah, wrong thread, this is not about
the larger stubs. :)

**Pull request closed without merging**
