### PR TITLE
coff-go32-exe: support variable-length stubs (attempt 2)

### PR DESCRIPTION
**Pull request by jwt27**

### CODE REVIEW

**Comment by jwt27** [comment]
Breaks 27 test cases in `check-ld`.
No additional failures in `check-binutils` and `check-gas`.

**Comment by stsp** [comment]
Will you upstream this and other djgpp-related
patches to binutils? I wonder why do we have the
unupstreamed custom patches.

**Comment by jwt27** [comment]
If I can get this to work, then yes, that is the plan.
As for the other patches, I didn't write them so I don't know what they all do or if they break other targets. But at the very least we need those ldscripts fixed upstream.

**Comment by jwt27** [comment]
Last commit fixes 17 test cases. 10 more to go.

**Comment by jwt27** [comment]
All the test cases succeed now. Problem now is, it doesn't work at all.
```
$ binutils/objdump.exe -x 2kstub.exe

2kstub.exe:     file format coff-go32-exe
2kstub.exe
architecture: i386, flags 0x00000132:
EXEC_P, HAS_SYMS, HAS_LOCALS, D_PAGED
start address 0x00000054

D:/msys64/home/JW/build-binutils/binutils/.libs/objdump.exe: failed to read symbol table from: 2kstub.exe
D:/msys64/home/JW/build-binutils/binutils/.libs/objdump.exe: error message was: invalid operation

$ binutils/objdump.exe -x bigstub.exe

bigstub.exe:     file format coff-go32-exe
bigstub.exe
architecture: i386, flags 0x00000132:
EXEC_P, HAS_SYMS, HAS_LOCALS, D_PAGED
start address 0x00000054

D:/msys64/home/JW/build-binutils/binutils/.libs/objdump.exe: failed to read symbol table from: bigstub.exe
D:/msys64/home/JW/build-binutils/binutils/.libs/objdump.exe: error message was: invalid operation

$ binutils/strip-new.exe -o test.exe -s 2kstub.exe
D:/msys64/home/JW/build-binutils/binutils/.libs/strip-new.exe: 2kstub.exe: file in wrong format

$ binutils/strip-new.exe -o test.exe -s bigstub.exe
D:/msys64/home/JW/build-binutils/binutils/.libs/strip-new.exe: bigstub.exe: file in wrong format
```
edit: I see what the problem is but I don't know how to fix it, without introducing hacks in the target-independent code. I'm sure that won't be accepted.

**Comment by jwt27** [comment]
Miraculously, someone very recently decided to make the check_format hook return a function pointer for cleanup.  This callback could then reset the file origin and I wouldn't need to introduce any extra hacks.  It's almost like they were reading my mind.

But still it doesn't work.  Reading does, but `ld` produces malformed exes in some cases.  It looks like only certain offsets are relative to the start of the COFF data while others are relative to the overall file, it's not very consistent.

**Comment by jwt27** [comment]
Okay, I got it to work now.  Will do some further testing, then if no other problems come up I'll submit this to GNU.

**Comment by stsp** [comment]
Do you mean it passes now all possible tests?
That's really a great news!
Let me know when I need to switch my project
to your package, or switch my djgpp ppa, or
anything else of that sort.

**Comment by jwt27** [comment]
The tests all pass now.  But when I try to compile my own code the assembler isn't working for some reason:
```
{standard input}: Assembler messages:
{standard input}:26255: Error: missing string
{standard input}:26256: Warning: .loc outside of .text
{standard input}:26256: Error: junk at end of line, first unrecognized character is `1'
{standard input}:26258: Warning: .loc outside of .text
{standard input}:26258: Error: junk at end of line, first unrecognized character is `1'
{standard input}:26259: Warning: .loc outside of .text
{standard input}:26259: Error: junk at end of line, first unrecognized character is `1'
{standard input}:26270: Error: missing string
{standard input}:26271: Warning: .loc outside of .text
{standard input}:26271: Error: junk at end of line, first unrecognized character is `2'
{standard input}:26275: Warning: .loc outside of .text
{standard input}:26275: Error: junk at end of line, first unrecognized character is `2'
{standard input}:26276: Warning: .loc outside of .text
{standard input}:26276: Error: junk at end of line, first unrecognized character is `2'
{standard input}:26280: Warning: .loc outside of .text
{standard input}:26280: Error: junk at end of line, first unrecognized character is `2'
{standard input}:26307: Error: missing string
{standard input}:26308: Warning: .loc outside of .text
{standard input}:26308: Error: junk at end of line, first unrecognized character is `3'
{standard input}:26310: Warning: .loc outside of .text
{standard input}:26310: Error: junk at end of line, first unrecognized character is `3'
{standard input}:26311: Warning: .loc outside of .text
{standard input}:26311: Error: junk at end of line, first unrecognized character is `3'
{standard input}:26320: Error: junk at end of line, first unrecognized character is `1'
{standard input}:26320: Internal error in add_lineno at ../../binutils-gdb/gas/config/obj-coff.c:422.
Please report this bug.
src/cpu_exception.cpp:294:1: fatal error: error writing to -: Invalid argument
  294 | }
      | ^
compilation terminated.
```
It's most likely not caused by my changes but I need to confirm what it is.  I'm thinking it's because 64k+ relocation support is still missing, although the error messages don't suggest that.

Anyway, my PPA already includes your djgpp patches so that should be good to use for dosemu2.

**Comment by stsp** [comment]
Where is it?
The search for "djgpp" at LP only gives mine.

**Comment by jwt27** [comment]
https://launchpad.net/~jwt27/+archive/ubuntu/djgpp-toolchain
Not sure why it doesn't show up in search. Maybe because it's a personal package and not a LP-hosted project.

**Comment by stsp** [comment]
https://launchpadlibrarian.net/469622402/buildlog_ubuntu-eoan-amd64.comcom32_0.1~alpha1-98-df2daca+202003190204~ubuntu19.10.1_BUILDING.txt.gz
```
i586-pc-msdosdjgpp-gcc -Wall -O2 -finline-functions -Wmissing-declarations  -c command.c -o command.o
make[1]: i586-pc-msdosdjgpp-gcc: Command not found
make[1]: *** [Makefile:41: command.o] Error 127
```

I build-depend on "djgpp" package.
Either it doesn't get binaries by depends,
or you don't have symlinks.

**Comment by jwt27** [comment]
Package `djgpp` is just libc and stubify etc.  You need `gcc-djgpp`.

**Comment by stsp** [comment]
Why not to make it a meta package
that installs everything needed?

**Comment by jwt27** [comment]
That is more or less what `gcc-djgpp` does, since it depends on `djgpp` and `binutils-djgpp`. So then you have everything you need.  The only things missing are gdb and some man/info pages that will conflict with native gcc.

**Comment by stsp** [comment]
OK, I can do that.
However, this is a consistency question.
E.g. if you have binutils-djgpp which is only
binutils, then the one would expect gcc-djgpp
to be gcc only.
Plus my package is called djgpp.
So are you sure this is your last naming
scheme? It would be good to think twice
and look how other packagers do that
(like for fedora) before letting the users
to switch, because then it will be too
late to change.

**Comment by jwt27** [comment]
I think this makes sense. `gcc-djgpp` is just gcc, but it depends on the other packages to work. Other cross toolchains on Ubuntu/Debian follow a similar scheme (although they split it up further with `g++`, `libstdc++`, etc being separate packages).  Maybe `djgpp` could be renamed to `libc-djgpp` or something, but there's more in that package than just libc.

**Comment by jwt27** [comment]
The assembler errors appear to have been caused by `--enable-targets=all`. I don't know why that happens. Everything else seems to work now so once I finish writing commit msgs and changelogs I think this is good to submit.

**Comment by jwt27** [comment]
merged upstream in commit 4d095f5 :)

**Comment by stsp** [comment]
I can only see these commits in your
fork of bminor/binutils-gdb, but not in
the original repo.

**Comment by jwt27** [comment]
The bminor mirror is lagging behind a bit.  You can see it on git://sourceware.org/git/binutils-gdb.git

**Pull request closed without merging**
